export const WORKFLOW_STEPS = {
  LOADING: 'loading',
  INFO: 'info',
  EXTRACT: 'extract',
  CLASSIFY: 'classify',
  VERIFY: 'verify',
  CONCLUDE: 'conclude',
};

export const STEP_ORDER = [
  WORKFLOW_STEPS.LOADING,
  WORKFLOW_STEPS.INFO,
  WORKFLOW_STEPS.EXTRACT,
  WORKFLOW_STEPS.CLASSIFY,
  WORKFLOW_STEPS.VERIFY,
  WORKFLOW_STEPS.CONCLUDE,
];

// CLASSIFY와 VERIFY가 같은 섹션을 공유
export const STEP_SECTION_MAP = {
  [WORKFLOW_STEPS.LOADING]: WORKFLOW_STEPS.LOADING,
  [WORKFLOW_STEPS.INFO]: WORKFLOW_STEPS.INFO,
  [WORKFLOW_STEPS.EXTRACT]: WORKFLOW_STEPS.EXTRACT,
  [WORKFLOW_STEPS.CLASSIFY]: WORKFLOW_STEPS.CLASSIFY, // CLASSIFY 섹션
  [WORKFLOW_STEPS.VERIFY]: WORKFLOW_STEPS.CLASSIFY, // VERIFY도 CLASSIFY 섹션
  [WORKFLOW_STEPS.CONCLUDE]: WORKFLOW_STEPS.CONCLUDE,
};

export const STEP_LABELS = {
  [WORKFLOW_STEPS.LOADING]: 'Loading',
  [WORKFLOW_STEPS.INFO]: 'Info',
  [WORKFLOW_STEPS.EXTRACT]: 'Extract',
  [WORKFLOW_STEPS.CLASSIFY]: 'Classify',
  [WORKFLOW_STEPS.VERIFY]: 'Verify',
  [WORKFLOW_STEPS.CONCLUDE]: 'Conclude',
};
